### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Arcensoth** [Arcensoth/pyckaxe#1]
### General
- [ ] Blocks with block states
- [ ] Block entities with NBT schema
- [ ] Entities with NBT schema
- [ ] Items with NBT schema
- [ ] Selectors and selector arguments
- [ ] Convenience constants
    - [ ] Blocks (instances)
    - [ ] Entities (instances)
    - [ ] Effects (symbols)
    - [ ] Enchantments (symbols)
    - [ ] Items (instances)
    - [ ] Objectives (symbols)
    - [ ] Particles (symbols)
    - [ ] Sounds (symbols)
- [ ] Datapack assets
    - [ ] Advancements
    - [ ] Functions
    - [ ] Loot Tables
    - [ ] Recipes
    - [ ] Structures
    - [ ] Tags
- [ ] Blocks
- [ ] Entities
- [ ] Items
- [ ] Commands
    - [ ] advancement
    - [ ] ban
    - [ ] ban_ip
    - [ ] banlist
    - [ ] bossbar
    - [x] clear
    - [ ] clone
    - [ ] data
    - [ ] datapack
    - [ ] debug
    - [ ] defaultgamemode
    - [ ] deop
    - [ ] difficulty
    - [x] effect
    - [ ] enchant
    - [ ] execute
        - [ ] align
        - [ ] anchored
        - [x] as
        - [x] at
        - [ ] facing
        - [x] if/unless block
        - [ ] if/unless blocks
        - [ ] if/unless entity
        - [ ] if/unless score
        - [ ] in
        - [ ] positioned
        - [ ] rotated
        - [x] run
        - [ ] store
    - [ ] experience
    - [ ] fill
    - [ ] function
    - [ ] gamemode
    - [ ] gamerule
    - [ ] give
    - [ ] help
    - [ ] kick
    - [ ] kill
    - [ ] list
    - [ ] locate
    - [ ] me
    - [ ] msg
    - [ ] op
    - [ ] pardon
    - [ ] pardon_ip
    - [ ] particle
    - [ ] playsound
    - [ ] publish
    - [ ] recipe
    - [ ] reload
    - [ ] replaceitem
    - [ ] save_all
    - [ ] save_off
    - [ ] save_on
    - [x] say
    - [ ] scoreboard
    - [ ] seed
    - [x] setblock
    - [ ] setidletimeout
    - [ ] setworldspawn
    - [ ] spawnpoint
    - [ ] spreadplayers
    - [ ] stop
    - [ ] stopsound
    - [ ] summon
    - [x] tag
    - [ ] team
    - [x] teleport
    - [ ] tell
    - [ ] tellraw
    - [x] time
    - [ ] title
    - [x] tp
    - [x] trigger
    - [ ] w
    - [ ] weather
    - [ ] whitelist
    - [ ] worldborder
    - [ ] xp
